### ISSUE TITLE
Possible wrong value in converting most of the values

### ISSUE THREAD

**Issue by sagrawal31** [misund/hex-to-rgba#360]
I'm trying to convert `#66ffffff` to RGBa without passing the alpha as 2nd parameter-

# Actual Behaviour 

`rgba(102, 255, 255, 1)`

# Expected Behaviour

`rgba(255, 255, 255, 0.4)` as `66` is 40% transparent https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4.

**Comment by sagrawal31** [comment]
Debug the code and came to know that the two-digit alpha needs to be at the end while I'm expecting it to be at the start.

**Comment by misund** [comment]
The alpha value of a css hex is at the end. [Details are available here.](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#rgb_colors)

**Comment by sagrawal31** [comment]
Thanks for pointing out again!
