### ISSUE TITLE
Doesn't work in IE11

### ISSUE THREAD

**Issue by eltonjuan** [misund/hex-to-rgba#8]
Not sure what you're targeting as far as browser support but the following line blows up in IE11:  https://github.com/misund/hex-to-rgba/blob/6987950f59aeb765fcd1d39906a84fec0a2bb0fd/src/index.js#L1

This is because `String.prototype.startsWith` isn't supported as shown in this table: http://kangax.github.io/compat-table/es6/#test-String.prototype.startsWith

**Comment by eltonjuan** [comment]
Opened PR https://github.com/misund/hex-to-rgba/pull/9 to address this issue.

**Comment by misund** [comment]
Thanks for pointing this out - I've only used this in projects with polyfills on the client side, so I never encountered the issue myself.
